import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Provider from "./components/provider";
import { getCurrentUser } from "./lib/session";
import Headerfalse from "./components/headerfalse";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  const user = await getCurrentUser()

  return (
    <html  lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-purple-100`}>

        {!user?.name ? (
          (<Provider>
            <Headerfalse/>
            {children}
            </Provider>)
        ) : 
        (<Provider>
          <Header/>
          {children}
          </Provider>)}

      </body>
    </html>
  );
}
